Repository AllanSaleh/capstone-project-online-healing, pull requests merged in 2021-07, with the labels that each got.

#97 Responsive NavBar
  src/App.js
  src/Components/AddNewCard/AddNewCard.js
  src/Components/CreditCard/CreditCard.js
  src/Components/Footer/Footer.js
  src/Components/NavBar/Avatar.png
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/Polygon1.svg
  src/Components/PurchaseTicket/Purchase.js
  src/Components/WorkingWithHealling/Frame.svg
  src/Components/WorkingWithHealling/Working.js
Labels: Responsiveness, enhancement

#89 Responsive thank you
  src/App.js
  src/Components/ThankYou/ThankYou.js
Labels: Responsiveness, enhancement

#91 Responsive blog slider
  src/App.js
  src/Components/Home/RecentBlogs.js
  src/Components/PurchaseTicket/Purchase.js
Labels: Responsiveness, enhancement

#92 working with healing is responsive now
  src/App.js
  src/Components/WorkingWithHealing/WorkingWithHealing.js
Labels: Responsiveness, enhancement

#93 Teamshowcaseresponsive
  src/Components/TeamShowcase/TeamCard.js
  src/Components/TeamShowcase/TeamPage.js
Labels: Responsiveness, enhancement

#94 added Responsiveness to "CommunicationSection", "TicketSection", and …
  src/Components/CreateAccount/CreateAccount.jsx
  src/Components/CreateAccount/InputField.jsx
  src/Components/Home/Card.jsx
  src/Components/Home/CommunicationSection.jsx
  src/Components/Home/TicketSection.jsx
  src/mockdata/data.js
Labels: Responsiveness

#96 Responsive login
  src/App.js
  src/Components/Careers/Careers.jsx
  src/Components/Description/Description.jsx
  src/Components/Login/login.jsx
  src/Components/landing page/Group 117.svg
  src/Components/landing page/landingpage.jsx
Labels: Responsiveness, enhancement

#98 Responsive careers
  src/App.js
  src/Components/Careers/Careers.jsx
  src/Components/Careers/Hiring.js
  src/Components/Careers/OpeningSection.js
  src/Components/Careers/Position.js
Labels: Responsiveness, enhancement

#100 Responsive contact
  src/App.js
  src/Components/AboutPage/Founding.js
  src/Components/AboutPage/Healing.js
  src/Components/Contact Page/ContactPage.js
  src/Components/Contact Page/FirstSection.js
  src/Components/Contact Page/SecondSection.js
Labels: Responsiveness, enhancement

#99 Responsive about
  src/App.js
  src/Components/AboutPage/AboutPage.js
  src/Components/AboutPage/Founding.js
  src/Components/AboutPage/Healing.js
  src/Components/Contact/ContactPage.js
  src/Components/Contact/ContactPic.svg
  src/Components/Contact/FirstSection.js
  src/Components/Contact/SecondSection.js
  src/Components/Footer/Footer.js
Labels: Responsiveness, enhancement

#102 Res signup
  src/App.js
  src/Components/Home/video-call-icon.svg
  src/Components/landing page/landingpage.jsx
  src/Components/signup/signup.jsx
Labels: Responsiveness, enhancement

#110 IntegratingFirebase
  package.json
  src/App.js
  src/Components/SignUpPage/SignUpPage.jsx
  src/Firebase/Firebase.js
  src/Firebase/index.js
  src/Utilities/FirebaseUtilities.js
  src/firebase.js
  src/mockdata/data.js
  yarn.lock
Labels: enhancement
